### ISSUE TITLE
RamblerInitialAssemblyCollector class_conformsToProtocol ?

### ISSUE THREAD

**Issue by mochalovroman** [rambler-ios/RamblerTyphoonUtils#14]
Прошу прощения что по-русски, хочу сделать issue быстро и вернуться к своей задаче.

Суть проблемы:
если мы в каждом Assembly говорим
`
@interface LalaLalaAssembly : TyphoonAssembly <RamblerInitialAssembly>
` 
то у нас все отлично, все Assembly имплементящие этот протокол будут инициированы.

Но если вы такой же параноик как я и любите базовые классы и используете следующий подход:

```
#import <Typhoon/Typhoon.h>
#import <RamblerTyphoonUtils/RamblerInitialAssembly.h>

@interface BaseTyphoonAssembly : TyphoonAssembly <RamblerInitialAssembly>
@end 
```

А потом все Assembly уже наследуете от него:

```
#import "BaseTyphoonAssembly.h"

@interface ConfigurableSettingAssembly : FFBaseTyphoonAssembly
@end
```

То тогда ни одна Assembly не будет автоматически инициирована.

Проблема кроется в RamblerInitialAssemblyCollector в функции class_conformsToProtocol который проверяет только текущий класс на то конформит ли он протокол, но не ходит вниз по его родителям. Сама Apple говорит в анотации к class_conformsToProtocol вот что:

```
@note You should usually use NSObject's conformsToProtocol: method instead of this function.
```

**Comment by etolstoy** [comment]
Спасибо, добавим в новой версии.
