### ISSUE TITLE
clang: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by feng-tianyou** [rambler-ios/RamblerTyphoonUtils#15]
ld: library not found for -lPods-RamblerTyphoonUtils_Example-RamblerTyphoonUtils
clang: error: linker command failed with exit code 1 (use -v to see invocation)

and how did i do?thanks

**Comment by etolstoy** [comment]
Hi, @DaisukeZJY. Looks like this is the problem with your project configuration. Show me your Podfile please.
