### ISSUE TITLE
Security problems

### ISSUE THREAD

**Issue by alexgarbarev** [rambler-ios/RamblerTyphoonUtils#16]
Hi everyone.
Our customer used security scanners to check app for security issues. Our app used `RamblerTyphoonUtils`.

Scanner complained with:

```
Signed integer strlen at line 64 of /Pods/RamblerTyphoonUtils/Code/Testing/AssemblyTesting/RamblerTyphoonAssemblyTestUtilities.m specifies size of memory to allocate.
```

```
66.      char buffer[1 + strlen(attributes)];
```

And I can agree that stack allocation with unpredictable length can be dangerous, or at least looks like.

I suggest removing that method for getting property type and use

```
[TyphoonIntrospectionUtils typeForPropertyNamed: inClass: ]
```

for that.
Aslo see

```
[TyphoonIntrospectionUtils propertiesForClass: upToParentClass:]
```

I think these methods can be handy, since RamblerTyphoonUtils depends on Typhoon

**Comment by etolstoy** [comment]
Hi, @alexgarbarev! Thanks for your report, we'll fix it ASAP.
