### ISSUE TITLE
dyld: Library not loaded: @rpath/XCTest.framework/XCTest

### ISSUE THREAD

**Issue by scodeit** [rambler-ios/RamblerTyphoonUtils#23]
Hello, i have a crush for this error:
dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /Users/macbook/Library/Developer/CoreSimulator/Devices/XXXX/data/Containers/Bundle/Application/XXXX/xxxx.app/Frameworks/RamblerTyphoonUtils.framework/RamblerTyphoonUtils
  Reason: image not found

**Comment by suriksarkisyan** [comment]
Hi, @dzxt . Try to install as recommended [here](https://github.com/rambler-digital-solutions/RamblerTyphoonUtils#installation).
You should use `pod 'RamblerTyphoonUtils/AssemblyCollector'` for main target and `pod 'RamblerTyphoonUtils/AssemblyTesting'` for test target.
You can also try to resolve it by adding `weak_framework` for XCTest in `Build Settings` > `Other Linker Flags` but first variation is better and should work definitely.

**Comment by scodeit** [comment]
thank u @suriksarkisyan , now i setup my podfile correctly - everything work.
