### ISSUE TITLE
Test finishing as succeeded, if array of dependencies has an extra dependency

### ISSUE THREAD

**Issue by vasilenkoigor** [rambler-ios/RamblerTyphoonUtils#4]
Hey, guys.

Recently I found strange issue with RamblerTyphoonUtils/AssemblyTesting.
For example: 

I have some assembly with components. Some component has one dependency, for example some Service. When I writing test for this component and create array dependencies with one extra dependency, for example:

``` objective-c
NSArray *dependencies = @[service, secondExtraService];
```

This test finished as succeeded, however this component need one dependency in this case. 
This is normal behaviour?

**Comment by vasilenkoigor** [comment]
After watching code of AssemblyTesting, I am convinced that function 

``` objective-c
[self verifyTargetDependency:result withClass:expectedClass dependencies:dependencies];
```

doesn't verify case if count dependencies of component less or greater than dependencies array.

Maybe it makes sense to implement this case like new feature? Is it possible?

**Comment by etolstoy** [comment]
Thanks for reporting!

It's possible to verify that all of the passed dependencies exist in the target class, we've just overlooked this case. Do you want to make a PR? :)

As for another part of your question - currently it's not possible to check if we are verifying all of the object dependencies. That's because we can't determine which of the properties should be injected by Typhoon, and which - manually in runtime.

**Comment by vasilenkoigor** [comment]
@igrekde It will be great if you add case that verify passed dependencies exist in the target class.
 What   can I do for PR? However, It will be nice for my growing experience, if you let me implement this case and make pull request.

Thanks for explanation my another second part of my question.

**Comment by etolstoy** [comment]
Look at the [class](https://github.com/rambler-ios/RamblerTyphoonUtils/blob/master/Code/AssemblyTesting/RamblerTyphoonAssemblyTests.m), especially at lines 35-40. You can do something similar - check if passed dependencies selectors exist in `allProperties` NSDictionary.

**Comment by etolstoy** [comment]
btw, I'm going for a vacation, so I'll hardly be able to make code review before the January 10.

**Comment by vasilenkoigor** [comment]
Thanks for your hint for me. 
Can you make code review after New Year vacation, if I'll be make pull request?

**Comment by etolstoy** [comment]
Yes, of course! Maybe @mogol will do it even sooner.

**Comment by vasilenkoigor** [comment]
Great! 
I wish you nice vacation ;)
