### ISSUE TITLE
Pod issue

### ISSUE THREAD

**Issue by Antowkos** [rambler-ios/RamblerTyphoonUtils#9]
Hi! I'm using cocoapods in my project with `use_frameworks!` option. Because of that i have error in `AssemblyCollector.h` - `'AssemblyCollector/RamblerInitialAssembly.h' file not found`.

Please, edit `import`s by deleting `AssemblyCollector/` part.

If you want to reproduce it - just install `pod "RamblerTyphoonUtils/AssemblyCollector"` with `use_frameworks!` option, import `AssemblyCollector.h` anywhere and try to run project.

**Comment by Antowkos** [comment]
Actually, ViperMcFlurry has the same issue in `IntermoduleDataTransfer.h`.

**Comment by alexgarbarev** [comment]
I'm having same problem, using cocoapods without frameworks.
it says file not found on line:

```
#import "AssemblyCollector/RamblerInitialAssembly.h"
```

inside AssemblyCollector.h

**Comment by alexgarbarev** [comment]
I believe cocoapods installation requires `#import "RamblerInitialAssembly.h"` without folder part. It works like that for me.

**Comment by etolstoy** [comment]
Sorry for the long delay! I've fixed the issue and updated pod to version 1.3.1.
